# Generated by Django 4.2 on 2023-04-19 10:01

from django.db import migrations, models
import enumchoicefield.fields
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='read',
            name='MPAN',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='read',
            name='datafields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='read',
            name='filesource',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='read',
            name='meterSN',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='read',
            name='typeofline',
            field=enumchoicefield.fields.EnumChoiceField(default=todo.models.TypeOfReadLine['_026'], enum_class=todo.models.TypeOfReadLine, max_length=4),
        ),
    ]
